name: My First Job

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: List and read files
          run: |
            ls -la
            cat README.md

        - name: install cowsay
          run: sudo apt-get update && sudo apt-get install cowsay

        - name: Generate ASCII artwork 
          run: cowsay -f dragon "run for cover,.... iam dragon" >> dragon.txt
