name: My First Job

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
        - name: Welcome message
          run: echo "Hello, world!"

        - name: list the files in the repository
          run: ls -la

        - name: read the README.md file
          run: cat README.md
